# Generated by Django 5.1 on 2024-08-18 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=100)),
                ('sending_time', models.DateTimeField()),
                ('file_data', models.BinaryField(max_length=50000000)),
                ('image_format', models.CharField(max_length=5)),
            ],
        ),
    ]
